### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [jsnell/ratas#1]
I would like to point out that an identifier like "[`_TIMER_WHEEL_H`](https://github.com/jsnell/ratas/blob/922496c369b7c38a1d5b48c831db2358316ed175/src/timer-wheel.h#L85)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jsnell** [comment]
Thanks, should be fixed now.

**Comment by elfring** [comment]
Thanks for [your improvement of an affected include guard](https://github.com/jsnell/ratas/commit/1ad6ef21f531a02ff34b381d0b1472cda3c4dd8a).
